#!/usr/bin/env python

import sys, yaml, pkg_resources

# Main function

if __name__ == '__main__':            

    # Load plugins from pkg_resources

    plugins = {
        entry_point.name: entry_point.load()
        for entry_point in pkg_resources.iter_entry_points('yamljsonmodel.plugins')
    }

    # Parse YAML files on command line

    for filename in sys.argv[1:]:

        with open(filename, 'r') as stream:
            
            # Parse YAML and send objects in the document to appropriate plugin

            y = yaml.load(stream)
            
            for obj in y:
                
                kind = obj['kind']
                
                if not plugins.has_key(kind):
                    raise Exception('No plugin called %s' % kind)
                
                plugin = plugins[kind]
                objcopy = obj.copy()
                del(objcopy['kind'])
                
                plugin.process_yaml_object(kind, objcopy)
