#!/usr/bin/env python

import sys, yaml
import yamljsonmodel

# Main function

if __name__ == '__main__':            

    # Parse YAML files on command line

    for filename in sys.argv[1:]:

        with open(filename, 'r') as stream:
            
            # Parse YAML and send objects in the document to appropriate plugin

            ydoc = yaml.load(stream)

            for tname, tvalue in yamljsonmodel.process_yaml_document(ydoc):
                print('---\n%s\n---' % tname)
                print(tvalue)
